export const SET_USER_PLANTS = 'SET_USER_PLANTS';

export const SET_USER_DETAILS = 'SET_USER_DETAILS'

export const REMOVE_USER_DETAILS = 'REMOVE_USER_DETAILS'

export const SET_USER_SETTINGS = 'SET_USER_SETTINGS'

export const SET_NOTIFICATIONS_TOKEN = 'SET_NOTIFICATIONS_TOKEN'