export const SET_USER_PLANTS = 'SET_USER_PLANTS';

export const REMOVE_USER_DETAILS = 'REMOVE_USER_DETAILS'

export const SET_USER_SETTINGS = 'SET_USER_SETTINGS'

export const SET_NOTIFICATIONS_TOKEN = 'SET_NOTIFICATIONS_TOKEN'

export const SHOW_TOAST = 'SHOW_TOAST'

export const HIDE_TOAST = 'HIDE_TOAST'
